SIMPLE_SETTINGS = {
    'OVERRIDE_BY_ENV': True,
}

OPENAI_API_KEY = ''
TG_TOKEN = ''
SECRET_INVITE = ''
SQLITE_PATH = ''
OPENAI_MODEL = ''

YANDEX_FOLDERID = ''
YANDEX_SEARCH_URL = ''
YANDEX_SEARCH_API_KEY = ''

EXECUTOR_BASE_URL = ''
TELEGRAM_BASE_URL = ''
