SIMPLE_SETTINGS = {
    'OVERRIDE_BY_ENV': True,
}

OPENAI_BASE_URL = 'https://api.openai.com/v1'
OPENAI_API_KEY = ''
TG_TOKEN = ''
SECRET_INVITE = ''
POSTGRES_DSN = ''
OPENAI_MODEL = 'gpt-4o'

YANDEX_FOLDERID = ''
YANDEX_SEARCH_URL = ''
YANDEX_SEARCH_API_KEY = ''

EXECUTOR_BASE_URL = ''
TELEGRAM_BASE_URL = ''

PROXY: str | None = None
TG_PROXY: str | None = None

STATSD_HOST = 'localhost'
STATSD_PREFIX = 'openai-all-stars.tgbot'

SENTRY_DSN = ''

HOST_INTERNAL = 'localhost'

CHAT_MESSAGES_LIMIT = 10

PAYMENT_URL_PREFIX = ''
